stdio.c: fix compilin error due to -Werror=unused-but-set-variable
../../lib/stdio.c: In function '_PrintHex':
../../lib/stdio.c:174:6: error: variable 'cnt' set but not used [-Werror=unused-but-set-variable]
../../lib/stdio.c:170:22: error: variable 'flagl' set but not used [-Werror=unused-but-set-variable]
../../lib/stdio.c: In function 'strtoul':
../../lib/stdio.c:414:16: error: variable 'strtoul_err' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors